@startuml
left to right direction
actor Менеджер
actor Инженер
actor Наблюдатель

Менеджер --> (Создать проект)
Менеджер --> (Назначить дефект)
Менеджер --> (Закрыть дефект)
Инженер --> (Создать/редактировать дефект)
Инженер --> (Перевод статуса)
Наблюдатель --> (Просмотр отчётов)
(Просмотр отчётов) --> (Сводка по статусам)
@enduml
